name: Build Check

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: choco install make

    - name: Run distcheck
      run: make distcheck_windows
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: choco install make

    - name: Run distcheck
      run: make distcheck_apple
