name: Build Check

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: choco install make

    - name: Run distcheck
      run: make distcheck
